### PR TITLE
fix esp32c3 boot loop

### LINKED ISSUE #54: Stuck in Boot Loop on ESP32C3 (Seeed XIAO ESP32C3)
**Describe the bug**
Microcontroller ends up in safe mode soon after flashing due to a boot loop. After the initial flashing process I was able to add it to HomeAssistant, but ever since power cycling it after that initial flash, nothing helps to resolve the issue. It boot loops and gets stuck in safe mode, HA cannot reach it.

**To reproduce**
1. Flash with the attached config
2. Observe Serial Logs

**Expected behavior**
The device should boot successfully and remain stable without entering a boot loop or safe mode.

**Logs and configuration**

*Firmware config*
```yaml
esphome:
  name: stromzaehler
  friendly_name: Stromzähler

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: arduino

external_components:
  - source: github://jensrossbach/esphome-ferraris-meter@v1.4.1
    components: [ferraris]

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxx"

ota:
  - platform: esphome
    password: "xxxxxxxxxxxxxxxxxx"

wifi:
  ssid: "xxxxxxxxxxxxxxxxxx"
  password: "xxxxxxxxxxxxxxxxxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Stromzaehler Fallback Hotspot"
    password: "xxxxxxxxxxxxxxxxxx"

captive_portal:

ferraris:
  id: ferraris_meter
  digital_input: GPIO10
  rotations_per_kwh: 375
  debounce_threshold: 300
  energy_start_value: last_energy_value
    
# numeric sensors
sensor:
  - platform: ferraris
    # sensor for current power consumption
    power_consumption:
      name: Momentanverbrauch
    # sensor for energy meter reading
    energy_meter:
      name: Verbrauchszähler
  # sensor for Wi-Fi signal strength
  - platform: wifi_signal
    name: Wi-Fi Signal
    update_interval: 60s

# binary sensors
binary_sensor:
  - platform: ferraris
    # sensor for indicating detected rotation during calibration mode
    rotation_indicator:
      name: Umdrehungsindikator
  # sensor for wireless connection status
  - platform: status
    name: Status

# text sensors
text_sensor:
  - platform: wifi_info
    # sensor providing the IP address of the ESP microcontroller
    ip_address:
      name: IP Adresse

# number components
number:
  # import entity holding last energy meter reading from Home Assistant
  - platform: homeassistant
    id: last_energy_value
    entity_id: input_number.stromzaehler_letzter_wert
  # number used to manually overwrite the energy meter
  - platform: template
    id: target_energy_value
    name: Manueller Zählerstand
    icon: mdi:counter
    unit_of_measurement: kWh
    device_class: energy
    entity_category: config
    mode: box
    optimistic: true
    min_value: 0
    max_value: 1000000
    step: 0.01

# switch components
switch:
  - platform: ferraris
    # switch used to activate or deactivate the calibration mode
    calibration_mode:
      name: Kalibrierungsmodus

# button components
button:
  # button used to trigger the manual overwriting of the energy meter
  - platform: template
    name: Verbrauchszähler überschreiben
    icon: mdi:download
    entity_category: config
    on_press:
      - ferraris.set_energy_meter:
          id: ferraris_meter
          value: !lambda |-
            float val = id(target_energy_value).state;
            return (val >= 0) ? val : 0;
```

*Serial logs*

```log
[19:51:50]Build:Feb  7 2021
[19:51:50]rst:0x3 (RTC_SW_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
[19:51:50]Saved PC:0x40381a90
WARNING Decoded 0x40381a90: esp_restart_noos_dig at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/esp_system/esp_system.c:44 (discriminator 1)
[19:51:50]SPIWP:0xee
[19:51:50]mode:DIO, clock div:1
[19:51:50]load:0x3fcd6100,len:0x438
[19:51:50]load:0x403ce000,len:0x918
[19:51:50]load:0x403d0000,len:0x24e4
[19:51:50]entry 0x403ce000
[19:51:50][I][logger:171]: Log initialized
[19:51:50][C][safe_mode:079]: There have been 9 suspected unsuccessful boot attempts
[19:51:50][D][esp32.preferences:114]: Saving 1 preferences to flash...
[19:51:50][D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[19:51:50][I][app:029]: Running through setup()...
[19:51:50][D][number:012]: 'Manueller Zählerstand': Sending state 0.000000
[19:51:51][D][sensor:094]: 'Momentanverbrauch': Sending state 0.00000 W with 1ESP-ROM:esp32c3-api1-20210207
[19:51:51]Build:Feb  7 2021
[19:51:51]rst:0x3 (RTC_SW_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
[19:51:51]Saved PC:0x40381a90
WARNING Decoded 0x40381a90: esp_restart_noos_dig at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/esp_system/esp_system.c:44 (discriminator 1)
[19:51:51]SPIWP:0xee
[19:51:51]mode:DIO, clock div:1
[19:51:51]load:0x3fcd6100,len:0x438
[19:51:51]load:0x403ce000,len:0x918
[19:51:51]load:0x403d0000,len:0x24e4
[19:51:51]entry 0x403ce000
[19:51:51][I][logger:171]: Log initialized
[19:51:51][C][safe_mode:079]: There have been 10 suspected unsuccessful boot attempts
[19:51:51][D][esp32.preferences:114]: Saving 1 preferences to flash...
[19:51:51][D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[19:51:51][E][safe_mode:086]: Boot loop detected. Proceeding to safe mode
[19:51:51][E][component:164]: Component safe_mode set Error flag: unspecified
```

**Context information**
 - ESPHome version: 2024.12.2
 - Ferraris Meter version: 1.4.1
 - Microcontroller type: Seeed XIAO ESP32C3

**Additional Information**

- The microcontroller works normally using a minimal configuration without the ferraris component.
- The device was tested with USB power and separate 5V power.

**Edit 13.02.25**

After leaving the microcontroller powered on throughout the night, it apparently got out of the boot loop at some point and began functioning as expected. Power-cycling or re-flashing it, however, restores the erroneous behavior.

### PR DESCRIPTION
**Pull request by ospringauf**
In FerrarisMeter, the member pointer m_debounce_threshold_number (type number::Number*) was not initialized in the constructor.

Fixes #54

# ESP32-C3 boot loop / crash on startup (Load access fault)

This document describes a boot-loop issue observed when using this Ferraris meter ESPHome component on an **ESP32-C3** (e.g. “Supermini”) and the fix that resolves it.

## Symptoms

- The device resets very early during boot, often right after the log line:
  - `Setting up Ferraris Meter...`
- Serial log shows a Guru Meditation crash:
  - `Guru Meditation Error: Core 0 panic'ed (Load access fault)`
- The decoded backtrace points into:
  - `esphome::EntityBase::has_state() const`
  - called from `esphome::ferraris::FerrarisMeter::setup()`.

This looks like a “boot loop” (repeated resets). Adding bulk capacitance may not help because this is a **software crash**, not a brownout.

## Root cause

In `FerrarisMeter`, the member pointer `m_debounce_threshold_number` (type `number::Number*`) was **not initialized** in the constructor.

- Uninitialized pointers may contain random non-null values.
- In `FerrarisMeter::setup()` the code checks `if (m_debounce_threshold_number != nullptr)` and then calls `m_debounce_threshold_number->has_state()`.
- If the uninitialized pointer happens to be non-null, the `has_state()` call dereferences an invalid address, causing a **Load access fault** and immediate reboot.

This explains why the device could “sometimes boot”: the pointer contents differ between runs/builds.

## Fix

The fix is to **explicitly initialize** `m_debounce_threshold_number` to `nullptr` in the constructor initializer list.

- File: [components/ferraris/ferraris_meter.cpp](components/ferraris/ferraris_meter.cpp)
- Change: add `, m_debounce_threshold_number(nullptr)` next to the other `number::Number*` initializations.

### Additional hardening (unrelated but crash-class)

A second issue was also fixed:

- Logging used the wrong format specifier for a `uint64_t` rotation counter (`%u` instead of `%llu`).
- On ESP32 targets, `printf`-style format mismatches are undefined behavior and can corrupt the stack.

- File: [components/ferraris/ferraris_meter.cpp](components/ferraris/ferraris_meter.cpp)
- Change: log `m_rotation_counter` via `%llu` and cast to `unsigned long long`.

## How to verify

1. Flash the firmware with the updated component.
2. Watch the serial log.
3. The crash should no longer occur immediately after `Setting up Ferraris Meter...`.

If you still see resets, check the reset reason:

- **Brownout** messages → power supply / wiring / sensor current draw.
- **Watchdog** messages → long blocking code or excessive work in callbacks.
- **Load access fault / IllegalInstruction** → still a software crash (collect a backtrace).

## Workarounds (if you cannot update the component)

There is no reliable configuration-only workaround for an uninitialized pointer bug.

If you are stuck on an older version:

- Remove the component from the build or temporarily disable it to confirm the crash source.
- Then update to a version that includes the initialization fix.

### CODE REVIEW

File: components/ferraris/ferraris_meter.cpp [hunk 1]
```diff
@@ -440,15 +441,15 @@ namespace esphome::ferraris
...
+        ESP_LOGD(TAG, "Set energy meter:  %.2f kWh (%llu rotations)", value, m_rotation_counter);
 
         update_energy_counter();
     }
 
     void FerrarisMeter::set_rotation_counter(uint64_t value)
     {
         m_rotation_counter = value;
-        ESP_LOGD(TAG, "Set rotation counter:  %u rotations", m_rotation_counter);
+        ESP_LOGD(TAG, "Set rotation counter:  %llu rotations", (unsigned long long) m_rotation_counter);
```
Comment (jensrossbach) [inline components/ferraris/ferraris_meter.cpp]: The type cast is superfluous as `m_rotation_counter` is already `uint64_t` (and at the other places, it is also not there).
